### ISSUE TITLE
OpenStack doesn't install on Windows

### ISSUE THREAD

**Issue by it-praktyk** [OpenStackCookbook/vagrant-openstack#14]
I know that your "priority is currently to get the book written" but I would like to log that a "helper environment" doesn't install correctly on Windows.

I try to troubleshoot this process by myself but I stack.

I've changed roles/runplaybooks/tasks/main to 

```yaml
---
- block:
    - name: Run Setup Hosts Playbook
      shell: openstack-ansible setup-hosts.yml -vvv > /vagrant/setup-hosts.log 2>1
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-hosts.log

  rescue:
    - name: Running openstack-ansible setup-hosts.yml
      shell: openstack-ansible --forks 1 setup-hosts.yml -vvv > /vagrant/setup-hosts-fallback.log 2>1
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-hosts-fallback.log

- block:
    - name: Run Infrastructure Playbooks
      shell: openstack-ansible --forks 2  setup-infrastructure.yml -vvv > /vagrant/setup-infrastructure.log 2>1
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-infrastructure.log

  rescue:
    - name: Running openstack-ansible setup-infrastructure.yml
      shell: openstack-ansible --forks 1 setup-infrastructure.yml -vvv > /vagrant/setup-infrastructure-fallback.log 2>1
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-infrastructure-fallback.log

- name: Configure Galera for HA Proxy
  shell: /vagrant/galera_haproxy.sh

- block:
    - name: Run OpenStack Playbooks
      shell: openstack-ansible --forks 2  setup-openstack.yml -vvv > /vagrant/setup-openstack.log 2>1
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-openstack.log

  rescue:
    - name: Running openstack-ansible setup-openstack.yml
      shell: openstack-ansible --forks 1 setup-openstack.yml -vvv > /vagrant/setup-openstack-fallback.log 2>1
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-openstack-fallback.log
```
and gathered logs I paste as [the gist](https://gist.github.com/it-praktyk/9adf98b9c6d6485d596f44079fa34875).

Can you look at them? I don't have idea how it fails

```ansible
TASK [runplaybooks : Run Setup Hosts Playbook] *********************************
ok: [controller-01]

TASK [runplaybooks : Run Infrastructure Playbooks] *****************************
fatal: [controller-01]: FAILED! => {"changed": true, "cmd": "openstack-ansible --forks 2 setup-infrastructure.yml -vvv >
 /vagrant/setup-infrastructure.log 2>1", "delta": "0:02:38.787154", "end": "2017-11-08 19:57:50.586691", "failed": true,
 "msg": "non-zero return code", "rc": 4, "start": "2017-11-08 19:55:11.799537", "stderr": "", "stderr_lines": [], "stdou
t": "", "stdout_lines": []}

TASK [runplaybooks : Running openstack-ansible setup-infrastructure.yml] *******
fatal: [controller-01]: FAILED! => {"changed": true, "cmd": "openstack-ansible --forks 1 setup-infrastructure.yml -vvv >
 /vagrant/setup-infrastructure-fallback.log 2>1", "delta": "0:01:54.555336", "end": "2017-11-08 19:59:45.297158", "faile
d": true, "msg": "non-zero return code", "rc": 4, "start": "2017-11-08 19:57:50.741822", "stderr": "", "stderr_lines": [
], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/vagrant/install-openstack.retry

PLAY RECAP *********************************************************************
compute-01                 : ok=14   changed=10   unreachable=0    failed=0
controller-01              : ok=25   changed=16   unreachable=0    failed=2

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
PS C:\Users\Administrator\vagrant-openstack>
```

The related issue #4
